### ISSUE TITLE
[Bug Report] All WiiU roms listing as "roms" with the same picture in Retro Rom Library 

### ISSUE THREAD

**Issue by jakequi** [dragoonDorise/EmuDeck#1313]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

When the parser gets the Cemu roms, they're all named "roms" and share an image when you look at them in Retro Rom Library.

Reinstalled everything and regenerated the database, no luck.

┆Issue is synchronized with this [Trello card](https://trello.com/c/LAkrdIsW) by [Unito](https://www.unito.io)

**Comment by dragoonDorise** [comment]
@jakequi this should be fixed, can you try again?

**Comment by jakequi** [comment]
Still not working. How do I regenerate the database? Updated EmuDeck, reinstalled Rom Library, moved roms to wiiu/roms and just wiiu. Still broken

**Comment by flying-admin** [comment]
@jakequi  try deleting $HOME/emudeck/cache/roms_games.json and try again

**Comment by dragoonDorise** [comment]
[@jakequi](https://github.com/jakequi) try deleting $HOME/emudeck/cache/roms_games.json and try again

**Comment by jakequi** [comment]
Tried this already, just tried it again, all of my WiiU roms are still just
called "roms"
