### ISSUE TITLE
OneDrive Cloud Save setup hanging on "Installing CloudSave"

### ISSUE THREAD

**Issue by colinjmatt** [dragoonDorise/EmuDeck#1323]
### Prerequisite Steps

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I have checked the [EmuDeck Wiki](https://emudeck.github.io/)
- [X] I have read the [Troubleshooting Page](https://emudeck.github.io/troubleshooting/steamos/) on the EmuDeck Wiki

### What distro are you running?

SteamOS

### Which SteamOS Branch are you using?

Stable

### What happened?

When setting up OneDrive as the cloud save provider on 2.3.0, it hangs indefinitely on "Installing Cloudsave".

I've logged into OneDrive successfully using Chrome. I've left it for over 30 minutes and it does not move on. Looks like there's a "command not found error" in the log, but EmuDeck isn't handling that as it should.

I've provided log output below, which starts from the beginning of starting a cloud save setup for OneDrive up to when it just hangs indefinitely.

### Relevant log output

cloud_sync_stopService.log:
```shell
Failed to query root for drive "b!h5bQfCy0eU-q_lf9xluAT2_YavVe_IRGgVuaX554J0jzx2dhuPHUQ4DmjpRwsXmy": HTTP error 400 (400 Bad Request) returned body: "{\"error\":{\"code\":\"invalidRequest\",\"message\":\"ObjectHandle is Invalid\",\"innerError\":{\"date\":\"2024-09-28T12:21:06\",\"request-id\":\"2200787c-5bc3-4ef6-a105-75aa4ac4b8e1\",\"client-request-id\":\"2200787c-5bc3-4ef6-a105-75aa4ac4b8e1\"}}}"
```

emudeckApp.log:
```shell
[09/28/2024] setSetting rclone_provider Emudeck-OneDrive && setSetting cloud_sync_provider Emudeck-OneDrive 
[09/28/2024] stdout: Old value rclone_provider=Emudeck-DropBox
Updating: /home/deck/emudeck/settings.sh - rclone_provider= to rclone_provider=Emudeck-OneDrive
Old value cloud_sync_provider=Emudeck-DropBox
Updating: /home/deck/emudeck/settings.sh - cloud_sync_provider= to cloud_sync_provider=Emudeck-OneDrive
```

**Comment by GoldDa** [comment]
I'm having the same issue as above.
On 2.3.0. Emudeck.

**Comment by colinjmatt** [comment]
Cloud Sync and associated bugs are part of the public release though?

**Comment by GoldDa** [comment]
@dragoonDorise This is part of the public and recent version of Emudeck, 2.3.0

**Comment by dragoonDorise** [comment]
@colinjmatt @GoldDa sorry, this is about Cloud Backup, I was mistaken!

Can you please upload our rclone.log file?

**Comment by colinjmatt** [comment]
@dragoonDorise cloud_sync_stopService.log is the only log that generates an error, which I've provided for you already

**Comment by GoldDa** [comment]
> @colinjmatt @GoldDa sorry, this is about Cloud Backup, I was mistaken!
> 
> Can you please upload our rclone.log file?

[cloud_sync_createService.log](https://github.com/user-attachments/files/17402656/cloud_sync_createService.log)
[cloud_sync_startService.log](https://github.com/user-attachments/files/17402658/cloud_sync_startService.log)
[cloud_sync_stopService.log](https://github.com/user-attachments/files/17402659/cloud_sync_stopService.log)
[rclone.log](https://github.com/user-attachments/files/17402660/rclone.log)

Hi. These are some of the log files from my Steam deck. I tried to setup Onedrive one more. I recieved the success screen but the installation still takes forever, even with full bars of my Wifi. 
![20241016_084453](https://github.com/user-attachments/assets/b32a946f-a443-4522-90f2-4623c5c53a65)

Let me know if there's anything else needed.

**Comment by bepstein111** [comment]
Same exact thing here with Nextcloud.

**Comment by pa1kia** [comment]
having this same issue no matter which provider i choose, and my `Emulation/tools/rclone` folder is empty as well.

**Comment by RexSonic** [comment]
Same issue

**Comment by brandon57** [comment]
I'm having this issue too. Doesn't matter which service I choose.

**Comment by mjsztainbok** [comment]
I'm having this issue too and it happens every provider I've tried

**Comment by CaptainEffort** [comment]
Having the same issue with Google drive.

**Comment by GoldDa** [comment]
@dragoonDorise Hi. 

It seems like this case has gathered a lot of attention recently and many people are experiencing the same issue, but with also other cloud providers as well. 

I wanted to know if a fix is being worked on and if there's alternatives you can suggest until then. 

Thank you.

**Comment by dragoonDorise** [comment]
Fixed in 2.3.8!

**Comment by CaptainEffort** [comment]
Not fixed. Or partially fixed. Cloudsave gets “installed” but doesn’t work. Testing shows that everything worked except the two most important things, upload and download status.

![Image](https://github.com/user-attachments/assets/ba9ba218-c653-4053-85ca-b213f4bee5da)
