### ISSUE TITLE
Installation script not finishing, stuck in "completing installation"

### ISSUE THREAD

**Issue by regiimoep** [dragoonDorise/EmuDeck#454]
I'm running an unmodded Q4 Steam Deck, with a 512 GB SD Card installed. I tried executing EmuDeck and running the custom setup, but when the installation part of the script starts, it never finishes. The progress bar doesn't move, the folder hierarchy does not get created - it's stuck. The last console output reads it could create settings.sh, which I think comes from running the EmuDeck application, but not much else. 

I tried rebooting, I tried running the install on both local storage and the SD card, both to no avail.

Any help on what I am missing is greatly appreciated.

**Comment by nicholaicascio** [comment]
Plus one from myself. I tried restarting, reformatting, and re-downloading the installer. No such luck, stuck on "We are completing your installation" every time.

**Comment by nicholaicascio** [comment]
I noticed that after the failed install, I can back out and try to run the installer again and it actually takes me to the UPDATE screen (as if I had installed EmuDeck) but nothing is functional. So then I just have to uninstall.

**Comment by Godsbane** [comment]
Thanks for the reports, looking into it, but need to wait for dragoon to
see this in the morning. Hang tight. Sorry for the inconveniences.

**Comment by regiimoep** [comment]
https://www.reddit.com/r/emudeck/comments/y6n0s2/_/isrcbbp

This post says the selection process is stuck so it doesn't continue, and a way to alleviate this is to double select, first something you don't want, then continue, then go back and do it again.

Hope this can be fixed in the next release

**Comment by LiamDawe** [comment]
Well this was frustrating to find out while recording a video, yeah the installer as it is currently is broken it seems.

**Comment by h3x1e** [comment]
Yeah same here stuck on the 
"We are completing your instalation ..."
"Linkikng retroarch saves to the Emulation/saves folder ..."

**Comment by h3x1e** [comment]
> Yeah same here stuck on the "We are completing your instalation ..." "Linkikng retroarch saves to the Emulation/saves folder ..."

Okay scrap that, after 20mins it completed.

**Comment by regiimoep** [comment]
> Well this was frustrating to find out while recording a video, yeah the installer as it is currently is broken it seems but I can confirm the workaround linked above works...

Didn't for me actually, I tried using a custom directory and then internal storage, didn't pan out.

**Comment by danielmorgan** [comment]
Same issue, proposed workaround didn't work.

http://sprunge.us/8SgacJ

**Comment by nicholaicascio** [comment]
https://photos.app.goo.gl/xhhcLd2nZZNXtzAbA

I tried following the workaround mentioned above and also let it sit for 30 minutes on the installation screen. No progress...

**Comment by h3x1e** [comment]
Are you guys trying to install onto an SD card or internal or something else?
Just wondering because I fixed this issue by formatting my SD cast again so it shows up in the "Device Select" screen of the installer. SD Card, Internal or "Custom Location"

I selected Internal clicked "Next", then went "Back" and selected the SD Card option.

**Comment by nicholaicascio** [comment]
> Are you guys trying to install onto an SD card or internal or something else? Just wondering because I fixed this issue by formatting my SD card again so it shows up in the "Device Select" screen of the installer. SD Card, Internal or "Custom Location"
> 
> I selected Internal clicked "Next", then went "Back" and selected the SD Card option.

This seems to have worked. I'm still having some trouble though. I can't launch Steam ROM Manager. I'm thinking that the installation is still somewhat corrupt.

**Comment by Godsbane** [comment]
An updated AppImage has been published to hopefully mitigate these issues.

Another fix we've seen being helpful is setting 1.1.1.1 as your DNS provider. Would love some feedback from those still affected.

**Comment by nicholaicascio** [comment]
> An updated AppImage has been published to hopefully mitigate these issues.
> 
> Another fix we've seen being helpful is setting 1.1.1.1 as your DNS provider. Would love some feedback from those still affected.

Yup. I downloaded the update and I am now able to run Steam ROM Manager. Thanks for the hard work!

**Comment by jrupinski** [comment]
The issue still persists on custom install, selecting the custom install directory and going back to internal storage (and setting DNS to 1.1.1.1, just in case) worked.

**Comment by 1Yanik3** [comment]
Issue still seems to exist for me. Have tried internal and external locations. Any ideas?

**Comment by danielmorgan** [comment]
> An updated AppImage has been published to hopefully mitigate these issues.

This worked for me, thanks for the fix!

For future reference I was using the custom setup on an SD card.

**Comment by regiimoep** [comment]
The updated image doesn't do the trick for me, I have tried each Custom Mode there is (Internal Storage, SD Card, and custom directory) but all of them are still stuck in the exact same step. The only thing I have not tried yet is setting the DNS to 1.1.1.1, which I wouldn't know where to set tbh

**Comment by andyclarke** [comment]
It hasn't worked for me either. I've tried twice, uninstalling in between, and gets stuck both times. I also haven't tried setting the DNS explicitly but my network uses 1.1.1.1 through a PiHole and I can't see anything being blocked

**Comment by Godsbane** [comment]
> It hasn't worked for me either. I've tried twice, uninstalling in between, and gets stuck both times. I also haven't tried setting the DNS explicitly but my network uses 1.1.1.1 through a PiHole and I can't see anything being blocked

would you please try it explicitly? Linking the guide for anyone who doesn't know how.

https://github.com/dragoonDorise/EmuDeck/wiki/frequently-asked-questions#why-wont-emudeck-download

**Comment by soulcrash14** [comment]
I have tried everything so far. Reset the whole System, formatted the SD Card, set DNS as in the guide above.
The installation run through once, but rom manager did not oben. After uninstalling and trying again, the installation did not start again.

**Comment by andyclarke** [comment]
I followed the guide, to set the DNS and restarted. Still no joy. Still gets stuck on the "We are completing your installation..." page with the 'Exit' & 'Launch SRM' buttons disabled 🤷‍♂️

**Comment by soulcrash14** [comment]
I cannot really believe that this was my solution, but i tried a different Wifi Connection and it works...

**Comment by andyclarke** [comment]
I tried 'Easy mode' instead of custom and that didn't work. I then closed it and opened it again. Instead of uninstalling it I told it to 'Easy' update. Now it seems to be working as it is actually installing things when it wasn't before

**Comment by Godsbane** [comment]
i wonder if the toggles are just refreshing the state data. Going easy --> custom or vice versa.

**Comment by jrupinski** [comment]
For me what worked was removing all the leftover folders (including hidden folders) after uninstallation.

**Comment by regiimoep** [comment]
Setting the DNS to 1.1.1.1 and running the script again did the trick for me this time, installation ran and all is well in the world again.

**Comment by Godsbane** [comment]
As far as we can tell this is resolved - barring network (1.1.1.1, ipv6, etc) issues. Does anyone still have a problem here? I'd like to close this issue out.

**Comment by Godsbane** [comment]
Closing this. Open a new issue if this comes up again and it's not a network problem.
